role,role-binding,deployment and jenkins file

diff --git a/jenkins-ci-cd/lab-22/Jenkins_App/Jenkinsfile b/jenkins-ci-cd/lab-22/Jenkins_App/Jenkinsfile
--- a/jenkins-ci-cd/lab-22/Jenkins_App/Jenkinsfile
+++ b/jenkins-ci-cd/lab-22/Jenkins_App/Jenkinsfile
@@ -1,29 +1,75 @@
 pipeline {
     agent any
-    
+    environment {
+        IMAGE_NAME = 'anas587/kubernets-app-app'
+        DEPLOYMENT_FILE = 'deployment.yaml'
+    }
     stages {
-        stage('Build') {
+        stage('run unit tests') {
             steps {
-                sh 'mvn clean compile'
-            }
-        }
-        
-        stage('Test') {
-            steps {
+                sh 'echo "Running unit tests..."'
                 sh 'mvn test'
             }
         }
-        
-        stage('Package') {
+        stage('Build') {
             steps {
                 sh 'mvn package'
             }
         }
         
+        
         stage('Docker Build') {
             steps {
-                sh 'docker build -t jenkins-app .'
+                sh 'docker build -t $IMAGE_NAME:$BUILD_NUMBER .'
             }
+        }
+        stage('Docker Push') {
+            steps {
+                withCredentials([usernamePassword(credentialsId: 'DockerHub', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
+                    sh '''
+                        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
+                        docker push $IMAGE_NAME:$BUILD_NUMBER
+                    '''
+                }
+            }
+        }        
+        stage('delete image from local') {
+            steps {
+                sh 'docker rmi $IMAGE_NAME:$BUILD_NUMBER || true'
+            }
+        }
+        stage('Update Deployment File') {
+            steps {
+                sh '''
+                sed -i 's|image: .*|image: $IMAGE_NAME:$BUILD_NUMBER|' $DEPLOYMENT_FILE
+                '''
+            }
+        }
+        stage('Deploy to Kubernetes') {
+            steps {
+                withCredentials([
+                    string(credentialsId: 'ServiceAccount-Token', variable: 'TOKEN'),
+                    string(credentialsId: 'API-Server', variable: 'API_SERVER')
+                ]) {
+                    sh '''
+                        cd ../K8s_App
+                        kubectl apply -f $DEPLOYMENT_FILE -n ivolve --server=$API_SERVER --token=$TOKEN --insecure-skip-tls-verify=true
+                        kubectl rollout status deployment/nodejs-app -n ivolve --server=$API_SERVER --token=$TOKEN --insecure-skip-tls-verify=true
+                    '''
+                }
+            }
+        }
+    }
+    post {
+        always {
+            echo 'Pipeline execution completed'
+            sh 'docker logout || true'
+        }
+        success {
+            echo 'Pipeline executed successfully!'
+        }
+        failure {
+            echo 'Pipeline execution failed!'
         }
     }
 }
